### ISSUE TITLE
nodejs error when using server

### ISSUE THREAD

**Issue by jonasbrami** [bitfinexcom/bfx-hf-data-server#34]
> node examples/server-lowdb.js

  bfx:hf:models:adapter-lowdb loading from /home/quenouille/bfx-hf-data-server/db/dev.json +0ms
  bfx:hf:data-server websocket API open on port 8899 +0ms
  bfx:hf:data-server ws client connected +3s
  bfx:hf:data-server error processing message: TypeError: Cannot destructure property `exchange` of 'undefined' or 'null'.
    at module.exports (/home/quenouille/bfx-hf-data-server/lib/bt/sync_data.js:9:7)
    at module.exports (/home/quenouille/bfx-hf-data-server/lib/cmds/exec_bt.js:27:11)
    at DataServer.onWSMessage (/home/quenouille/bfx-hf-data-server/lib/server.js:345:5)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/quenouille/bfx-hf-data-server/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/quenouille/bfx-hf-data-server/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/home/quenouille/bfx-hf-data-server/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/quenouille/bfx-hf-data-server/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/quenouille/bfx-hf-data-server/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at Socket.socketOnData (/home/quenouille/bfx-hf-data-server/node_modules/ws/lib/websocket.js:900:35)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) +5ms
  bfx:hf:data-server:wss:send-error internal error (103) +0ms

Getting this error when running the data_backtest server part of ema_cross.py from bfx-hf-strategy-py and also the online_bt example of bfx-hf-backtest. 

Ubuntu 20.04 LTS
npm 6.14.4
Python 3.8.5

**Comment by robertkowalski** [comment]
good catch! fixed in https://github.com/bitfinexcom/bfx-hf-data-server/pull/37
